# Generated by Django 3.2.7 on 2023-12-17 11:03

import autoslug.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Property Title')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='title', unique=True)),
                ('ref_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Reference Code')),
                ('description', models.TextField(default='default description.. Update me please...', verbose_name='Property Description')),
                ('country', django_countries.fields.CountryField(default='CM', max_length=2, verbose_name='Country')),
                ('city', models.CharField(default='Bamenda', max_length=255, verbose_name='City')),
                ('postal_code', models.CharField(default='140-001', max_length=255, verbose_name='Postal Code')),
                ('street_address', models.CharField(max_length=255, verbose_name='Street Address')),
                ('property_number', models.IntegerField(default=112, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Property Number')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Property Price')),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, help_text='15% property tax charged on the property price', max_digits=6, verbose_name='Property Tax')),
                ('plot_area', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Area (sq ft)')),
                ('bedrooms', models.PositiveIntegerField(default=1, verbose_name='Bedrooms')),
                ('total_floors', models.PositiveIntegerField(default=0, verbose_name='Numbor of Floors')),
                ('bathrooms', models.PositiveIntegerField(default=0, verbose_name='Bathrooms')),
                ('avert_type', models.CharField(choices=[('For Sale', 'For Sale'), ('For Rent', 'For Rent'), ('Auction', 'Auction')], default='For Sale', max_length=50, verbose_name='Avert Type')),
                ('property_type', models.CharField(choices=[('House', 'House'), ('Apartment', 'Apartment'), ('Land', 'Land'), ('Commercial', 'Commercial'), ('Industrial', 'Industrial'), ('Office', 'Office'), ('Storage', 'Storage'), ('Parking', 'Parking'), ('Other', 'Other')], default='Other', max_length=20, verbose_name='Property Type')),
                ('cover_photo', models.ImageField(blank=True, default='/house_sample.jpg', null=True, upload_to='photos', verbose_name='Main Photo')),
                ('photo1', models.ImageField(blank=True, default='/interior_sample.jpg', null=True, upload_to='photos', verbose_name='Main Photo')),
                ('photo2', models.ImageField(blank=True, default='/interior_sample.jpg', null=True, upload_to='photos', verbose_name='Main Photo')),
                ('photo3', models.ImageField(blank=True, default='/interior_sample.jpg', null=True, upload_to='photos', verbose_name='Main Photo')),
                ('published_status', models.BooleanField(default=False, verbose_name='Published')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Total Views')),
                ('currency', models.CharField(blank=True, default='USD', max_length=3, null=True, verbose_name='Currency')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('garages', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Garages')),
                ('area_measurement', models.CharField(blank=True, default='sq ft', max_length=20, null=True, verbose_name='Area Measurement')),
                ('year_built', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Year Built')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='agent_buyer', to=settings.AUTH_USER_MODEL, verbose_name='Agent, Seller or Buyer')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='PropertyViews',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip', models.CharField(max_length=255, verbose_name='IP Address')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_views', to='properties.property')),
            ],
            options={
                'verbose_name': 'Total Views on Property',
                'verbose_name_plural': 'Total Property Views',
                'ordering': ['-created_at'],
            },
        ),
    ]
