# Generated by Django 3.2.7 on 2023-12-17 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='avert_type',
            new_name='advert_type',
        ),
        migrations.RemoveField(
            model_name='property',
            name='address',
        ),
    ]
