# Generated by Django 3.2.7 on 2022-06-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='photo1',
            field=models.ImageField(blank=True, default='/inerior_sample.jpg', null=True, upload_to='', verbose_name='Photo1'),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo2',
            field=models.ImageField(blank=True, default='/inerior_sample.jpg', null=True, upload_to='', verbose_name='Photo2'),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo3',
            field=models.ImageField(blank=True, default='/inerior_sample.jpg', null=True, upload_to='', verbose_name='Photo3'),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo4',
            field=models.ImageField(blank=True, default='/inerior_sample.jpg', null=True, upload_to='', verbose_name='Photo4'),
        ),
    ]
