# Generated by Django 3.2.7 on 2022-06-13 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_auto_20220613_0552'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProPertyVeiws',
            new_name='PropertyViews',
        ),
    ]
