# Generated by Django 3.2.7 on 2023-12-17 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_auto_20231217_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='photo1',
            new_name='photo_1',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='photo2',
            new_name='photo_2',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='photo3',
            new_name='photo_3',
        ),
    ]
