# Generated by Django 3.2.7 on 2022-06-13 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_auto_20220613_0810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='perperty_number',
            new_name='property_number',
        ),
    ]
