#!/bin/bash

set -o errexit

set -o nounset

# echo "Waiting for celery to start"

worker_ready() {
celery -A real_estate inspect ping 

}

until worker_ready; do
    >&2 echo 'Celery worker is unavailable - sleeping'
    sleep 1
done 
    >&2 echo 'Celery worker is up - continuing...'
exec "$@"


# flower \
#     --app=real_estate \
#     --broker="${CELERY_BROKER_URL}" \

celery -A real_estate flower \
    --broker="${CELERY_BROKER_URL}" \